before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version

language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx

matrix:
  include:
    - rvm: 1.9.3
      env: RDOC_VERSION="~>3.0"
  allow_failures:
    - rvm: rbx
